fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
      - id: black
        args: [--diff, --check]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a3
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c "rm test.db; cd admin_ui/src && python -m pytest tests/"
        language: system
        pass_filenames: false
        always_run: true
